name: C/C++ CI

on:
  push:
    branches: [ main, actions ]
  pull_request:
    branches: [ main ]

jobs:
  job:
    runs-on: ubuntu-20.04
    steps:
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
      - name: Conda environment
        run: conda create --yes --quiet --name cc3d_2020 python=3.7
      - name: Git clone build scripts
        run: git clone https://github.com/CompuCell3D/cc3d_build_scripts.git
      - name: Git clone build scripts
        run: source activate cc3d_2020 && conda install -c conda-forge numpy scipy pandas jinja2 webcolors vtk=8.2 pyqt pyqtgraph deprecated qscintilla2 jinja2 chardet cmake swig=3 requests && conda install -c compucell3d tbb_full_dev && pip install libroadrunner && pip install antimony
      - name: source activate base
        run: cd cc3d_build_scripts/linux/400/ && python build.py --prefix=~/410_auto --source-root=../ --build-dir=~/410_auto_build --version=4.1.0 --cores=2 --conda-env-name=cc3d_2020
